[[redirects]]
  from = "/api/*"
  to = "https://zomatoopspro.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  CI = "false"